// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error)
	CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error)
	CreateParticipant(ctx context.Context, arg CreateParticipantParams) (Participant, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAccount(ctx context.Context, id int64) error
	DeleteEvent(ctx context.Context, id int64) error
	DeleteParticipant(ctx context.Context, id int64) error
	GetAccount(ctx context.Context, id int64) (Account, error)
	GetEvent(ctx context.Context, id int64) (Event, error)
	GetLocation(ctx context.Context, event int64) (Location, error)
	GetSession(ctx context.Context, refreshToken string) (Session, error)
	GetUser(ctx context.Context, username string) (User, error)
	ListAccount(ctx context.Context, arg ListAccountParams) ([]Account, error)
	ListEvent(ctx context.Context, arg ListEventParams) ([]Event, error)
	ListParticipant(ctx context.Context, arg ListParticipantParams) ([]Participant, error)
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error)
	UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error)
	UpdateLocation(ctx context.Context, arg UpdateLocationParams) (Location, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
